name: pizza_tz
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  badges: ^3.1.2
  bloc_test: ^9.1.4
  pizza_repository:
    path: packages/pizza_repository

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
